address/urls.py
from django.urls import path
from address import views



app_name = "address"

urlpatterns = [
    path('address/',views.AddressCreateView.as_view(),name='address'),
    path('addresslist', views.AddressListView.as_view(), name='address_list'),
    path('address/<int:pk>/', views.AddressUpdateView.as_view(), name='address-update'),
    
   
    
]

cart/urls.py
from django.urls import path,re_path
from cart import views
app_name = "cart"

urlpatterns = [
    path('<int:pk>/', views.add_to_cart,name='cart'),
    path('order-summary', views.order_details, name="order_summary"),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete_item'),
    path('success/', views.success, name='purchase_success'),
    path('checkout/', views.checkout, name='checkout'),
    re_path('update-transaction/(?P<token>[-\w]+)/', views.update_transaction_records,
        name='update_records'),
    path('buy_now/<int:pk>/', views.buy_now,name='buy_now'),
    path('local/', views.local, name='local'),
    
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Shop Store'

app_name = "search"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace="products")),
    path('search/', include("search.urls",namespace="search")),
    path('cart/', include("cart.urls",namespace="cart")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('address/', include("address.urls",namespace="address")),

    path('category/', include("category.urls",namespace="category")),

     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views
app_name = "products"
urlpatterns = [
    path('home/', views.HomePageView.as_view(),name='home'),
    path('about/',views.AboutPageView.as_view(), name='about'),
    path('data/', views.DataPageView.as_view(), name='data'),  
    path('products/', views.product_list_view, name='product'), 
    path(r'', views.ProductListView.as_view(), name='list'),
    path('details/<int:pk>/',views.ProductDetailView.as_view(), name='detail'),
    
]

cart/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models


from products.models import Product
# Create your models here.
User = settings.AUTH_USER_MODEL

class OrderItem(models.Model):
    product = models.OneToOneField(Product,blank=True,on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default= False)
    date_added = models.DateTimeField(auto_now_add=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.title


class Order(models.Model):
    owner = models.ForeignKey(User,null=True,blank=True,on_delete=models.CASCADE)
    ref_code = models.CharField(max_length= 15)
    is_ordered = models.BooleanField(default= False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now_add=True)

    def get_cart_items(self):

        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

class Transaction(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

cart/views.py
from accounts.models import User
from products.models import Product
from django.shortcuts import render, redirect, get_object_or_404
from cart.extra import generate_order_id
from .models import OrderItem,Order,Transaction
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from cart.extra import generate_order_id
from django.conf import settings
import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your vews here.




def get_user_pending_order(request):
    user_profile = get_object_or_404(User,pk= request.user.pk)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        return order[0]
    return 0

@login_required(login_url='/accounts/login/')
def add_to_cart(request,**kwargs):
    
    user_profile = get_object_or_404(User,pk= request.user.pk)
 
    product = Product.objects.filter(id=kwargs.get('pk', "")).first()
    
    order_item, status = OrderItem.objects.get_or_create(product=product)

    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
       
        user_order.ref_code = generate_order_id()
        user_order.save()

    
    messages.success(request, "item added to cart")
    
    return redirect(reverse('products:list'))
 
@login_required(login_url='/accounts/login/')
def buy_now(request,**kwargs):
    
    user_profile = get_object_or_404(User,pk= request.user.pk)
 
    product = Product.objects.filter(id=kwargs.get('pk', "")).first()
    
    order_item, status = OrderItem.objects.get_or_create(product=product)

    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
       
        user_order.ref_code = generate_order_id()
        user_order.save()
        
    return redirect(reverse('address:address_list'))



@login_required(login_url='/accounts/login/')
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'cart/home.html', context)

@login_required(login_url='/accounts/login/')
def delete_from_cart(request, pk):
    item_to_delete = OrderItem.objects.filter(pk=pk)
    if item_to_delete.exists():
        item_to_delete[0].delete()
    return redirect(reverse('cart:order_summary'))





@login_required(login_url='/accounts/login/')
def checkout(request, **kwargs):

    existing_order = get_user_pending_order(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        token = request.POST.get('stripeToken', False)
        if token:
            try:
                charge = stripe.Charge.create(
                    amount=100*existing_order.get_cart_total(),
                    currency='inr',
                    description='Prodcut charge',
                    source=token,
                )

                return redirect(reverse('cart:update_records',
                        kwargs={
                            'token': token
                        })
                    )
            except stripe.error.CardError:
                messages.info(request, "Your card has been declined.")
        else:
            result = transact({
                'amount': existing_order.get_cart_total(),
                'payment_method_nonce': request.POST['payment_method_nonce'],
                'options': {
                    "submit_for_settlement": True
                }
            })

            if result.is_success or result.transaction:
                return redirect(reverse('cart:update_records',
                        kwargs={
                            'token': result.transaction.id
                        })
                    )
            else:
                for x in result.errors.deep_errors:
                    messages.info(request, x)
                return redirect(reverse('cart:checkout'))
            
    context = {
        'order': existing_order,
    
        'STRIPE_PUBLISHABLE_KEY': publishKey
    }

    return render(request, 'cart/checkout.html', context)

@login_required()
def update_transaction_records(request, token):
    order_purchase = get_user_pending_order(request)
    order_purchase.is_ordered=True
    order_purchase.date_ordered=datetime.datetime.now()
    order_purchase.save()
    
    order_items = order_purchase.items.all()
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())
    user_profile = get_object_or_404(User, username=request.user.username)
    amount = order_purchase.get_cart_total()
    transaction = Transaction(username = user_profile,
                            token=token,
                            order_id= order_purchase.id,
                            amount=  amount,
                            success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()


    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('accounts:my_profile'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'cart/purchase_success.html', {})

def local(request):
    return render(request,'cart/local.html')

cart/templates/cart/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet">

  <style>
  /**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

#card-element{
  width:40%;
  
}
  </style>
  
</head>

<body>
    {% include 'cart/messages.html' %}
    <div class="container">
    <section>
      <div class="row" id="tablerow">
      <div class="col-md-4 col-xs-12">
        <div class="panel panel-primary">
          
        
        </div>
      </div>
      <div class="col-md-8 col-xs-12">
        <table class="table">
          <tr>
            <td><h4>Order Summary</h4></td>
          </tr>
          <tr>
            <td>
              {% for item in order.get_cart_items %}
                <tr>
                  <td>{{ item }}</td>
                  <td>RS:{{ item.product.price }}</td>
                </tr>
              {% endfor %}
            </td>
          </tr>
          <tr>
            <td><strong>Order Total</strong> </td>
            <td> <strong>RS:{{ order.get_cart_total }}</strong></td>
          </tr>
        </table>
       
      </div>
     </div>
    </section>

    <script src="https://js.stripe.com/v3/"></script>
  <div class = "container">
    <form action="{%  url 'cart:checkout' %}" method="post" id="payment-form">
      {% csrf_token %}
      <div class="form-row">
        <label for="card-element">
          Credit or debit card
        </label>
        <div id="card-element">
          <!-- A Stripe Element will be inserted here. -->
        </div>
    
        <!-- Used to display form errors. -->
        <div id="card-errors" role="alert"></div>
      </div>
     
     
    <br> <button class="btn btn-primary">Submit Payment</button>
    </form>
  </div>  
  <script>
  // Create a Stripe client.
var stripe = Stripe('pk_test_YC88OFguJ7rtHPS9qQIRSSeI00TCMJdJUs');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
  </script>
</body>
</html>

cart/templates/cart/home.html
{% extends 'base/index.html' %} {% load static %} {% block pagecontent %}
{% load add_tags  %}
{% block scripts %}
  {{ block.super }}

  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  <script>

function myConfirm() {
  var result = confirm("Are You Sure?");
  if (result==true) {
   return true;
  } else {
   return false;
  }
}


    
    
    </script>
{% endblock scripts %}
<div class="container">
        {% include 'cart/messages.html' %}
        <div class="row">
            <table class="table table-hover table-bordered text-center">
                <thead>
                    <tr>
                     
                        <th  style="text-align: center" scope="col">No.</th>
                        <th style="text-align: center" scope="col">Item</th>
                        <th style="text-align: center" scope="col">Price</th>

                    </tr>
                </thead>

                {% for item in order.get_cart_items %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {{ item.product.title }}
                        <span class="pull-right">
                            <a href="{% url 'cart:delete_item' item.id %}"  class="text-danger" onclick="return myConfirm();">
                                <i class="fas fa-trash"></i>
                            </a>
                        </span>
                    </td>
                    <td>{{ item.product.price }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan=3> You have not added any items yet.</td>
                </tr>
                {% endfor %}
                <tr>
                    {% if order.get_cart_total != None %}
                    <td colspan=2>
                        <strong class="pull-right">Order Total:</strong>
                    </td>

                    <td colspan=1>
                        RS:
                        <strong>{{ order.get_cart_total }}</strong>
                    </td>
                    {% endif %}
                </tr>
                <tr>
                    <td colspan=1>
                        <a href="/" class="btn btn-warning pull-left">
                            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
                        </a>
                    </td>
                    <td colspan=2>
                        {% if order.get_cart_items %}
                        <a href="{% url 'address:address_list' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
                        {% endif %}
                    </td>
                </tr>
            </table>

        </div>
   
        
    </section>

</div>
{% endblock %}

cart/templates/cart/local.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Shopping Cart</title>
    <style>
        td { text-align :center}
    </style>
   <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

</head>
<body>

    <button id="btnAdd" onclick="addToCart()" >Add To Cart</button>


</body>
</html>
<script>
console.log('working')
 if(localStorage.getItem('cart') == null){
 var cart = {};
 }
 else
 {
 cart = JSON.parse(localStorage.getItem('cart'));
 }
function addToCart() {
 var idstr = document.getElementById("btnAdd");
  if (cart[idstr]!= undefined){

  cart[idstr] = cart[idstr] + 1;
  }
  else
  {
   cart[idstr] = cart[idstr] = 1;
  }

  console.log('idstr')
  console.log(cart);
  localStorage.setItem('cart',JSON.stringify(cart));
};
</script>

cart/templates/cart/messages.html
{% if messages %}

<style type="text/css">
    div.messages{
        background-color: #ff6b6b;
        color: #f7fff7;
    }
    ul.messages{
        list-style-type: none;
    }


    div.messages{
        background-color: #ff6b6b;
        color: #f7fff7;
        width: 22%;
        height:50px;
        margin-bottom: 30px;
        font-size: 18px;
        text-align: center;
        transition-property: background, border-radius;
        transition-duration: .2s, 1s;
        transition-timing-function: linear, ease-in;
        transition-delay: 0s, 1s;
      
}
   

    ul.messages{
        list-style-type: none;
       
    }
</style>


<script>
    $(document).ready(function() {
        setTimeout(function(){ $('#message').hide(); }, 2000);
});

</script>

<div class='messages' id="message">

<ul class="messages">
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
{% endfor %}
</ul>

</div>
{% endif %}

cart/templates/cart/order_summary.html
{% extends 'base/index.html' %} {% load static %} {% block pagecontent %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span class="pull-right">
              <a href="{% url 'cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.product.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          RS<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'products:list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

cart/templates/cart/purchase_success.html
{% extends 'base/index.html' %} {% load static %} {% block pagecontent %}

    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'products:list' %}">Head back home</a>
{% endblock content %}

cart/templates/cart/stripe_default_form.html
<script src="https://js.stripe.com/v3/"></script>

<form action="." method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ STRIPE_PUBLISHABLE_KEY }}"
    data-amount="999"
    data-name="Shoping cart"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>