cart/urls.py
from django.urls import path,re_path
from cart import views
app_name = "cart"

urlpatterns = [
    path('<int:pk>/', views.add_to_cart,name='cart'),
    path('order-summary', views.order_details, name="order_summary"),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete_item'),
    path('success/', views.success, name='purchase_success'),
    path('checkout/', views.checkout, name='checkout'),
    re_path('update-transaction/(?P<token>[-\w]+)/', views.update_transaction_records,
        name='update_records'),
    path('buy_now/<int:pk>/', views.buy_now,name='buy_now'),
    path('local/', views.local, name='local'),
    
    
]

category/urls.py
from django.urls import path
from category import views
app_name = "category"

urlpatterns = [

    path('list/', views.CategoryListView.as_view(), name='category_list'),
    path('category_type/<int:pk>/', views.CategorytypeListView.as_view(), name='category_type'),
    path('category_product/<int:pk>/', views.ProductListCategory.as_view(), name='category_product'),
    
  
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Shop Store'

app_name = "search"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace="products")),
    path('search/', include("search.urls",namespace="search")),
    path('cart/', include("cart.urls",namespace="cart")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('address/', include("address.urls",namespace="address")),

    path('category/', include("category.urls",namespace="category")),

     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class CategoryType(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='category_list')
    categorytype = models.CharField(max_length=255)

    class Meta:
        ordering = ('categorytype',)
        verbose_name = 'categorytype'
        verbose_name_plural = 'categorytype'

    
    def __str__(self):
        return str(self.category) + ': ' + self.categorytype

category/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Category,CategoryType
from products.models import Product

# Create your views here.
def category(request):
    message = "Men Woman  kids"
    context = {
        "data":message
    }
    return render (request,'category/category_list.html',context)



class CategoryListView(ListView):
    template_name = 'category/category_list.html'
    model = Category

    
class CategorytypeListView(ListView):
    template_name = 'category/category_type.html'
    model = CategoryType

    def get_queryset(self, *args, **kwargs):
        cat_id = Category.objects.filter(id=self.kwargs['pk']).first()
        return CategoryType.objects.filter(category__name= cat_id)

class ProductListCategory(ListView):
    template_name = 'category/product_category.html'
    model = Product

    def get_queryset(self, *args, **kwargs):
        cat_id = CategoryType.objects.filter(id=self.kwargs['pk']).first()
       
        return Product.objects.filter(category = cat_id)

category/templates/category/category_list.html
{% extends 'base/index.html' %} {% load static %} {% block pagecontent %}
<style>
    .link {
        color:brown;
        text-decoration-line: none;
        font-size: 20px;
    }
</style>

<div class="container">
    <h3>Lif Of Category</h3>
    {% for obj in object_list %}
   <ul class="list-group">
      
     <li class="list-group-item"><a  href="{% url 'category:category_type' obj.pk  %}" class="link">{{obj.name}}</a></li>
           
    </ul>
    {% endfor %}
</div>
{% endblock %}

category/templates/category/category_type.html
{% extends 'base/index.html' %} {% load static %} {% block pagecontent %}
<style>
       .link {
            color:brown;
            text-decoration-line: none;
            font-size: 20px;
        }
    </style>
<div class="container">
    <h3>Lif Of   Category Type</h3>
    {% for obj in object_list %}
<ul class="list-group">
   
  <li class="list-group-item"><a href="{% url 'category:category_product'  obj.pk  %}" class="link">{{obj.categorytype}}</a></li>
        
 </ul>
 {% endfor %}
</div>
{% endblock %}

category/templates/category/product_category.html
{% extends 'base/index.html' %} {% load static %} {% block pagecontent %}

<section class="page-section portfolio" id="portfolio">
        <div class="container">
            <h3>List of the Products</h3>
            <div class="row">
                
{% for obj in object_list %}
{% include 'products/card.html' with instance=obj %}  
   
 {% endfor %}
</div>
</div>
</section>
{% endblock %}