accounts/urls.py
from django.urls import path
from django.conf import urls
from accounts import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy
app_name = "accounts"

urlpatterns = [
    path('register/',views.Register.as_view(),name='register'),
    path('login/', views.login_request, name="login"),
    path('logout/', auth_views.LogoutView.as_view(
        next_page=reverse_lazy('accounts:login'),
    ), name='logout'),
    path('profile/', views.my_profile, name='my_profile')
    
    
  
    
]

cart/urls.py
from django.urls import path,re_path
from cart import views
app_name = "cart"

urlpatterns = [
    path('<int:pk>/', views.add_to_cart,name='cart'),
    path('order-summary', views.order_details, name="order_summary"),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete_item'),
    path('success/', views.success, name='purchase_success'),
    path('checkout/', views.checkout, name='checkout'),
    re_path('update-transaction/(?P<token>[-\w]+)/', views.update_transaction_records,
        name='update_records'),
    path('buy_now/<int:pk>/', views.buy_now,name='buy_now'),
    path('local/', views.local, name='local'),
    
    
]

category/urls.py
from django.urls import path
from category import views
app_name = "category"

urlpatterns = [

    path('list/', views.CategoryListView.as_view(), name='category_list'),
    path('category_type/<int:pk>/', views.CategorytypeListView.as_view(), name='category_type'),
    path('category_product/<int:pk>/', views.ProductListCategory.as_view(), name='category_product'),
    
  
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Shop Store'

app_name = "search"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace="products")),
    path('search/', include("search.urls",namespace="search")),
    path('cart/', include("cart.urls",namespace="cart")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('address/', include("address.urls",namespace="address")),

    path('category/', include("category.urls",namespace="category")),

     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views
app_name = "products"
urlpatterns = [
    path('home/', views.HomePageView.as_view(),name='home'),
    path('about/',views.AboutPageView.as_view(), name='about'),
    path('data/', views.DataPageView.as_view(), name='data'),  
    path('products/', views.product_list_view, name='product'), 
    path(r'', views.ProductListView.as_view(), name='list'),
    path('details/<int:pk>/',views.ProductDetailView.as_view(), name='detail'),
    
]

templates/base/about.html
{% extends 'base/index.html' %}

{% block pagecontent %}
<section class="text-center my-5">

    <!-- Section heading -->
    <h2 class="h1-responsive font-weight-bold my-5">Why is it so great?</h2>
    <!-- Section description -->
    <p class="lead grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
  
    <!-- Grid row -->
    <div class="row">
  
      <!-- Grid column -->
      <div class="col-md-4">
  
        <i class="fas fa-chart-area fa-3x red-text"></i>
        <h5 class="font-weight-bold my-4">Analytics</h5>
        <p class="grey-text mb-md-0 mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit
          maiores aperiam minima assumenda deleniti hic.
        </p>
  
      </div>
      <!-- Grid column -->
  
      <!-- Grid column -->
      <div class="col-md-4">
  
        <i class="fas fa-book fa-3x cyan-text"></i>
        <h5 class="font-weight-bold my-4">Tutorials</h5>
        <p class="grey-text mb-md-0 mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit
          maiores aperiam minima assumenda deleniti hic.
        </p>
  
      </div>
      <!-- Grid column -->
  
      <!-- Grid column -->
      <div class="col-md-4">
  
        <i class="far fa-comments fa-3x orange-text"></i>
        <h5 class="font-weight-bold my-4">Support</h5>
        <p class="grey-text mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit maiores
          aperiam minima assumenda deleniti hic.
        </p>
  
      </div>
      <!-- Grid column -->
  
    </div>
    <!-- Grid row -->
  
  </section>
{% endblock %}

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Django Sample Site - {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  
    <!-- Theme CSS -->
    <link href="{% static  'css/freelancer.min.css' %}" rel="stylesheet">
  <!-- Theme CSS -->
  <link href="{% static  'css/freelancer.min.css' %}" rel="stylesheet">

  </head>
  <body>
    <div class="container">
      {% block pagecontent %}
      
      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  
    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  
    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>
  
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>
  </body>
</html>

templates/base/data.html
{% extends 'base/base.html' %}
<!-- Add this-->


    {% block pagecontent %}
    <div class="table-div">
      <table class="table">
        <thead>
          <tr>
            <th>Celebrity Name</th>
            <th>Net Worth</th>
          </tr>
        </thead>
        <tbody>
          {% for celebrity in data %}
          {data}
            <tr>
              <td>{{ celebrity.title }}</td>
              <td>$ {{ celebrity.description }}</td> <!--Modify this line-->
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% include 'base/var_bar.html' %}
    {% endblock %}

templates/base/header.html
{% load static %}


        <!-- <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static  'images/slider1.jpg' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static  'images/03.jpg' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static  'images/01.jpg' %}" class="d-block w-100" alt="...">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div> -->
         <div class="container">
    
        <img src="{% static  'images/slider1.jpg' %}" class="d-block w-100" alt="...">
        <br>
        <br>
        <marquee behavior="scroll" direction="left">
            <img src="{% static  'images/jumbo.jpg' %}" width="200" height="80" alt="Natural" />
           &nbsp; &nbsp;<img src="{% static  'images/mobile.jpg' %}" width="150" height="120" alt="Natural" />
           &nbsp; &nbsp; <img src="{% static  'images/add.jpg' %}" width="150" height="120" alt="Natural" />
           &nbsp; &nbsp; <img src="{% static  'images/timage.jpg' %}" width="150" height="120" alt="Natural" />
          </marquee>
          </div>

templates/base/index.html
<!DOCTYPE html> {% load static %} {% load add_tags   %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Online Shopping Store</title>

  <!-- Custom fonts for this theme -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Theme CSS -->
  <link href="{% static  'css/freelancer.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'products:list' %}">Shopping Store</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button"
        data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'products:list' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'category:category_list' %}">Category</a>
          </li>

          <li class="nav-item">

        
         
            <a href="{% url 'cart:order_summary' %}" class="btn btn-info btn-lg">
              <span class="glyphicon glyphicon-shopping-cart"></span>Cart {% cart_item_count request.user.username %}
            </a>
      

          </li>

        </ul>

      </div>

    </div>
    {% include 'search/search-form.html' %}
    {% if  request.user.is_authenticated %}
         <span style="color: white"> {{request.user.username}}</span>
    {% endif %}
    <ul class="nav navbar-nav navbar-right">
      <li>
          
        
              <a href="{% url 'accounts:login' %}">
                <span class="glyphicon glyphicon-user"></span>Login
              </a>
         
      
          
      </li>
      {% if  request.user.is_authenticated %}
      <li>
        
    
          <a href="{% url 'accounts:logout' %}">
              <span class="glyphicon glyphicon-log-out"></span>Logout
            </a>
    
      </li>
      {% endif %}
     
    </ul>
    </li>
    </ul>

  </nav>

  {% block pagecontent %} {% endblock %}
  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <div class="row">

        <!-- Footer Location -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Location</h4>
          <p class="lead mb-0">2215  Drive
            <br>Clark, MO 65243</p>
        </div>

        <!-- Footer Social Icons -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Around the Web</h4>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-facebook-f"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-twitter"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-linkedin-in"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-dribbble"></i>
          </a>
        </div>

        <!-- Footer About Text -->
        <div class="col-lg-4">
          <h4 class="text-uppercase mb-4">About shop Store</h4>
          <p class="lead mb-0">Welcome  to the shop store<br>
            <a href="#">Start Shopping</a>.</p>
        </div>

      </div>
    </div>
  </footer>

  <!-- Copyright Section -->
  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Akash </small>
    </div>
  </section>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>


  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>


  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Contact Form JavaScript -->
  <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
  <script src="{% static 'js/contact_me.js' %}"></script>

  <!-- Custom scripts for this template -->


</body>

</html>

templates/base/nav.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Online Shopping Store</title>

  <!-- Custom fonts for this theme -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Theme CSS -->
  <link href="{% static  'css/freelancer.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'list' %}">Shopping Store</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'list' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link"  href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link"  href="{% url 'list' %}">Products</a>
                </li>
             
            </ul>
           
      </div>
    
    </div>
   {%  include 'search/search-form.html' %}

  </nav>

  {% block content %}
  


 {% endblock %}
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Contact Form JavaScript -->
  <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
  <script src="{% static 'js/contact_me.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/freelancer.min.js' %}"></script>

</body>

</html>

templates/base/var_bar.html
<ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'list' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Products
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Mens</a>
            <a class="dropdown-item" href="#">Womens</a>
            <a class="dropdown-item" href="#">Kids</a>
        
        </li>
       
      </ul>