cart/urls.py
from django.urls import path,re_path
from cart import views
app_name = "cart"

urlpatterns = [
    path('<int:pk>/', views.add_to_cart,name='cart'),
    path('order-summary', views.order_details, name="order_summary"),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete_item'),
    path('success/', views.success, name='purchase_success'),
    path('checkout/', views.checkout, name='checkout'),
    re_path('update-transaction/(?P<token>[-\w]+)/', views.update_transaction_records,
        name='update_records'),
    path('buy_now/<int:pk>/', views.buy_now,name='buy_now'),
    path('local/', views.local, name='local'),
    
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Shop Store'

app_name = "search"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls',namespace="products")),
    path('search/', include("search.urls",namespace="search")),
    path('cart/', include("cart.urls",namespace="cart")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('address/', include("address.urls",namespace="address")),

    path('category/', include("category.urls",namespace="category")),

     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from search import views


app_name = "search"
urlpatterns = [
    path('', views.SearchProductListView.as_view(),name='query'),

]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.db.models import Q
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render, get_object_or_404, redirect
from products.models import Product
# Create your views here.
class SearchProductListView(ListView):
    '''Search  for  the products'''
    template_name = "search/search.html"
    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductListView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        # SearchQuery.objects.create(query=query)
        return context
    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q',None)
        if query is not None:
            return Product.objects.filter(Q(title__icontains=query) |
                  Q(description__icontains=query) |
                  Q(price__icontains=query)
                  )
        return Product.objects.featured()

       

search/templates/search/search-form.html
<form method='GET' action='{% url "search:query" %}' class="form my-2 my-lg-0 search-form">
        <div class='input-group'>
          <input class="form-control" type="text" placeholder="Search" name='q' aria-label="Search" value='{{ request.GET.q }}'>
          <span class='input-group-btn'>
              <button class="btn btn-outline-success" type="submit"> <span class="glyphicon glyphicon-search"></span> Search</button>
          </span>
          </div>
      </form>

search/templates/search/search.html
{% extends 'base/index.html' %}
{% load static %}

{% block pagecontent %}


{% for obj in object_list %}
{% include 'products/card.html' with instance=obj %}  
{% endfor %}

 <div class="container">
<div class='row  mb-3'>
        {% if query %}
        <div class='col-12' >
            Results for <b>{{ query }}</b>
            <hr/>
        </div>
        
    
        <div class='col-12 col-md-6 mx-auto py-5'>
                {%  include 'search/search-form.html' %}
    
        </div>
        <div class='col-12'>
            <hr>
        </div>
        {% endif %}
    </div>
    
</div>     

 {% endblock %}